apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: event-logger-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: factorial-to-logger
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-logger
