apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: factorial-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: source-to-factorial
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: rust-factorial-function
  reply:
    ref:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: Channel
      name: factorial-to-logger
